### ISSUE TITLE
"500 WinRMTransport. Bad HTTP response returned from server." errors

### ISSUE THREAD

**Issue by anl** [trondhindenes/ansibleroles-winreboot#2]
I'm getting a 500 error from WinRM during the "Get windows nodes with a pending reboot" task - the nodes reboot successfully, but Ansible returns an error _after_ they reboot, and the playbook aborts.

I only see issues with the WinRM transport when rebooting the remote systems (Windows 2012R2 servers); other windows modules work without issue on these machines.

ansible-playbook output:

```
$ ansible-playbook reboot.yml -i inventory.py

PLAY [Do a reboot] ************************************************************ 

TASK: [winreboot | Get windows nodes with a pending reboot] ******************* 
Traceback (most recent call last):
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 161, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 136, in _winrm_exec
    self.protocol.cleanup_command(self.shell_id, command_id)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/protocol.py", line 287, in cleanup_command
    rs = self.send_message(xmltodict.unparse(rq))
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/protocol.py", line 190, in send_message
    return self.transport.send_message(message)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/transport.py", line 110, in send_message
    raise WinRMTransportError('http', error_message)
WinRMTransportError: 500 WinRMTransport. Bad HTTP response returned from server.  Code 500
fatal: [pb082600-dc02.west.example.com] => failed to exec cmd PowerShell -NoProfile -NonInteractive -EncodedCommand [...]
Traceback (most recent call last):
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 161, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 136, in _winrm_exec
    self.protocol.cleanup_command(self.shell_id, command_id)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/protocol.py", line 287, in cleanup_command
    rs = self.send_message(xmltodict.unparse(rq))
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/protocol.py", line 190, in send_message
    return self.transport.send_message(message)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/transport.py", line 110, in send_message
    raise WinRMTransportError('http', error_message)
WinRMTransportError: 500 WinRMTransport. Bad HTTP response returned from server.  Code 500
fatal: [pb082600-dc01.west.example.com] => failed to exec cmd PowerShell -NoProfile -NonInteractive -EncodedCommand [...]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/ifs/home/aleonard/reboot.retry

pb082600-dc01.west.example.com : ok=0    changed=0    unreachable=1    failed=0   
pb082600-dc02.west.example.com : ok=0    changed=0    unreachable=1    failed=0  
```

Playbook I'm using:

```

---
- name: Do a reboot
  hosts: domain_controllers
  gather_facts: False
  roles:
    - role: winreboot
      winreboot_simulate: yes
```

This is on Ansible 1.9.2, installed in a virtualenv with the following modules:

```
Jinja2==2.8
MarkupSafe==0.23
PyYAML==3.11
ansible==1.9.2
ecdsa==0.13
isodate==0.5.4
netaddr==0.7.15
paramiko==1.15.2
pycrypto==2.6.1
pysphere==0.1.7
pyvmomi==5.5.0.2014.1.1
pywinrm==0.0.3
requests==2.7.0
six==1.9.0
xmltodict==0.9.2
```

Thanks for looking at this.

**Comment by trondhindenes** [comment]
anl, that is very strange. Could you try the following: Pull out the module from the role's library file and drop it in one of your "regular" library paths (or use ansible.cfg to point to a folder where you drop it) and try and run that module by itself:
`ansible myhost -m win_pendingreboot -a "reboot_behavior=if_required"`

By the way, I just found a bug in my doc. The role name is trondhindenes.win_reboot, so unless you haven't renamed it in the filesystem you need to change the role name in your yml. I'm updating my docs now.

**Comment by anl** [comment]
(I renamed the role in my file system; I'm using a git checkout as of 1e950ae.)

With "reboot_behavior" set to "if_required" there is no error (and no reboot done, as there isn't a pending reboot):

```
$ ansible first_dc -m win_pendingreboot -a "reboot_behavior=if_required" -i inventory.py
pb082600-dc02.west.example.com | success >> {
    "changed": false, 
    "pending_reboot": false
}
```

(If I change "reboot_behavior" to "always", forcing a reboot, I do get the same error as before:)

```
$ ansible first_dc -m win_pendingreboot -a "reboot_behavior=always" -i inventory.py
Traceback (most recent call last):
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 161, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/ansible/runner/connection_plugins/winrm.py", line 136, in _winrm_exec
    self.protocol.cleanup_command(self.shell_id, command_id)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/protocol.py", line 287, in cleanup_command
    rs = self.send_message(xmltodict.unparse(rq))
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/protocol.py", line 190, in send_message
    return self.transport.send_message(message)
  File "/ifs/home/aleonard/git/aleonard/push-button/virtualenv/local/lib/python2.7/site-packages/winrm/transport.py", line 110, in send_message
    raise WinRMTransportError('http', error_message)
WinRMTransportError: 500 WinRMTransport. Bad HTTP response returned from server.  Code 500
pb082600-dc02.west.example.com | FAILED => failed to exec cmd PowerShell -NoProfile -NonInteractive -EncodedCommand [...]
```

Thanks...

**Comment by trondhindenes** [comment]
anl I've only tested this on Ansible 2.0, but I've made some updates to make it a bit more robust. Would you mind updating the role and let me know how it goes?

**Comment by anl** [comment]
Thanks for the follow up - I'm still seeing the same error with the latest commits.  I'm wondering if this is a race condition - I'm launching VMs across a sometimes slow WAN to the other side of the continent.  I'll test further with some more local VMs and see if that makes any difference.

**Comment by trondhindenes** [comment]
Good stuff. I can do some testing over WANs as well.

**Comment by trondhindenes** [comment]
@anl did you get any further on this? I just realized I hadn't followed up on your issue.

**Comment by anl** [comment]
I suspect the underlying issue is in the WinRM communicator for Ansible.  I haven't had the time to dig into this as much as I'd like, and I haven't tested with Ansible 2.0 at all, so let's close this, at least for now.

Thanks!

**Comment by trondhindenes** [comment]
Will do. I'm not actually using Ansible's winrm at all, simply curling to the WinRM webservice to get its status. Please open a new one if you get into troubles on 2.0, there are some things we can do to troubleshoot.
